"use strict";

// articles catalog
var catalog = [
    // 1
    {
        id: "1",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/08/anon562.png",
        title: "Как посмотреть сторис анонимно?",
        labelTime: "5",
        labelReaders: "758",
        articleLink: "https://blog.instashpion.ru/kak-posmotret-storis-anonimno/",
    },
    // 2
    {
        id: "2",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/08/pic11-639x400.png",
        title: "Что делать если Инстаграм вылетает",
        labelTime: "6",
        labelReaders: "836",
        articleLink: "https://blog.instashpion.ru/chto-delat-esli-instagram-vyletaet/",
    },
    // 3
    {
        id: '3',
        img: 'https://blog.instashpion.ru/wp-content/uploads/2021/10/pexels-pavel-danilyuk-7120925-1-830x400.jpg',
        title: 'Как проследить за телефоном мужа без его ведома — 27 способов',
        labelTime: '12',
        labelReaders: '6358',
        articleLink: 'https://blog.instashpion.ru/kak-prosledit-za-telefonom-muzha/'
    },
    // 4
    {
        id: "4",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/07/3-1-870x400.jpg",
        title: "Как добавить активную ссылку на WhatsApp в Instagram",
        labelTime: "5",
        labelReaders: "821",
        articleLink: "https://blog.instashpion.ru/kak-dobavit-aktivnuju-ssylku-na-whatsapp-v-instagram/",
    },
    // 5
    {
        id: "5",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/07/2-1-662x400.jpg",
        title: "Включите родительский контроль в Instagram: защитите своих детей в Интернете!",
        labelTime: "4",
        labelReaders: "1146",
        articleLink: "https://blog.instashpion.ru/vkljuchite-roditelskij-kontrol-v-instagram-zashhitite-svoih-detej-v-internete/",
    },
    // 6
    {
        id: "6",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Dizajn-bez-nazvaniya-2.jpg",
        title: "Как удалить пост в инстаграм — с телефона и компьютера",
        labelTime: "3",
        labelReaders: "1413",
        articleLink: "https://blog.instashpion.ru/kak-udalit-post-v-instagram/",
    },
    {
        id: "7",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/05/insta-parsing-1.jpg",
        title: "Как использовать базу аккаунтов для продвижения в Инстаграм*",
        labelTime: "4",
        labelReaders: "963",
        articleLink: "https://blog.instashpion.ru/kak-ispolzovat-bazu-akkauntov-dlja-prodvizhenija-v-instagram/",
    },
    {
        id: "8",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/05/insta-ban-2-870x400.jpg",
        title: "Instagram* заблокирован: что будет с блогерами и брендами",
        labelTime: "5",
        labelReaders: "1489",
        articleLink: "https://blog.instashpion.ru/blogery_posle_blokirovki_instagram/",
    },
    {
        id: "9",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/05/insta-ban-770x400.jpg",
        title: "Законно ли пользоваться Instagram* и Facebook* после блокировки",
        labelTime: "3",
        labelReaders: "1415",
        articleLink: "https://blog.instashpion.ru/mozhno_li_-polzovatsja_instagram/",
    },
    {
        id: "10",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/08/banner_1.png",
        title: "Следи за любым пользователем в инстаграм бесплатно и анонимно",
        labelTime: "2",
        labelReaders: "1241",
        articleLink: "https://blog.instashpion.ru/sledi-za-ljubym-polzovatelem-v-instagram-besplatno-i-anonimno/",
    },
    {
        id: "11",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Okno-avtorizatsii-v-profil-na-sajte-Instagram-v-brauzere-e1645708281763-724x400.png",
        title: "Вход в инстаграм без регистрации — инструкция",
        labelTime: "4",
        labelReaders: "1240",
        articleLink: "https://blog.instashpion.ru/vhod-v-instagram-bez/",
    },
    {
        id: "12",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Dizajn-bez-nazvaniya-2.jpg",
        title: "Как удалить сообщения и переписку в инстаграм — инструкция",
        labelTime: "3",
        labelReaders: "1324",
        articleLink: "https://blog.instashpion.ru/kak-udalit-soobshheniya-i-perepisku-v-instagram/",
    },
    {
        id: "13",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Dizajn-bez-nazvaniya-4.jpg",
        title: "Не ставятся лайки в инстаграм — что делать?",
        labelTime: "4",
        labelReaders: "1201",
        articleLink: "https://blog.instashpion.ru/ne-stavyatsya-lajki-v-instagram-chto-delat/",
    },
    {
        id: "14",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Dizajn-bez-nazvaniya-2.jpg",
        title: "Как удалить пост в инстаграм — с телефона и компьютера",
        labelTime: "3",
        labelReaders: "1324",
        articleLink: "https://blog.instashpion.ru/kak-udalit-post-v-instagram/",
    },
    {
        id: "15",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/48B17725-8C34-4CC0-971B-01DA030549A0-830x400.jpeg",
        title: "Как скачать Инстаграм на компьютер — бесплатно на русском языке",
        labelTime: "3",
        labelReaders: "967",
        articleLink: "https://blog.instashpion.ru/kak-skachat-instagram/",
    },
    {
        id: "16",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/izobrazhenie_2022-01-27_023144-740x400.png",
        title: "Как восстановить пост в Инстаграме — из архива или после удаления",
        labelTime: "5",
        labelReaders: "1425",
        articleLink: "https://blog.instashpion.ru/kak-vosstanovit-post-v-instagrame/",
    },
    {
        id: "17",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/izobrazhenie_2022-01-27_023416-660x400.png",
        title: "Эмулятор для Инстаграм на компьютер — как пользоваться",
        labelTime: "4",
        labelReaders: "853",
        articleLink: "https://blog.instashpion.ru/emulyator-dlya-instagram/",
    },
    {
        id: "18",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/Dizajn-bez-nazvaniya.jpg",
        title: "Пропал аккаунт в инстаграм — что делать, как восстановить",
        labelTime: "4",
        labelReaders: "1389",
        articleLink: "https://blog.instashpion.ru/propal-akkaunt-v-instagram/",
    },
    {
        id: "19",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/izobrazhenie_2022-01-26_004453-830x400.png",
        title: "Как скрыть историю в Инстаграме от одного человека или ото всех — инструкция",
        labelTime: "3",
        labelReaders: "1452",
        articleLink: "https://blog.instashpion.ru/kak-skryt-istoriju-v-instagrame/",
    },
    {
        id: "20",
        img: "https://blog.instashpion.ru/wp-content/uploads/2022/01/izobrazhenie_2022-01-26_005440-830x400.png",
        title: "Как посмотреть, кто сохранил фото в Инстаграме в закладки — инструкция",
        labelTime: "5",
        labelReaders: "1025",
        articleLink: "https://blog.instashpion.ru/kak-posmotret-kto-sohranil-foto-v-instagrame/",
    },
];